[package]
name = "filament"
version = "0.1.0"
authors = ["David Campion <David.Campion@walmartlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.22.2"
tokio = "1.12.0"
